### ISSUE TITLE
Venture SPRINT News Todo-list

### ISSUE THREAD

**Issue by huan** [PreAngel/pre-angel.com#24]
- [ ] 2017.6, ruijun, 我经历快创的故事：学到了什么，有什么经验教训
- [ ] 2018.5, ruijun, 全悉科技经历：从创业教练到AI实战，找到了自己更适合做创业教练的结论
- [ ] 2018.12 ruijun, 我是如何开始接触 Google Design Sprint 的，为什么要做 Venture SPRINT
- [ ] 2019.3 venture-sprint, 我眼中的 Design 社区，和他们的 Google Design Sprint 运营工作
- [ ] 2019.6 venture-sprint, 从第一场 Google Design Sprint ，到华兴…… 从极客咖啡起步，到与清华大学合作
- [ ] 2019.8 venture-sprint, 香港科大EMBA一起AI创业大赛合作……
- [ ] 2019.9 venture-sprint, 与石榴社区（Designer社区）的合作：北京设计周……
